### ISSUE TITLE
Sequence Input - Change initial image with each frame

### ISSUE THREAD

**Issue by mlsnr** [yownas/shift-attention#16]
I'd like to use this effect on an image sequence from a video. Would it be possible to adapt the script, so each generated frame uses a different frame from the sequence as initial image?

It can be done manually, but it would require a full generation cycle for each frame, then handpicking the relevant frames and dumping many unnecessary images.

**Comment by yownas** [comment]
I can definitely see why this would be a nice effect... but I'm not sure if I know how to do it.  I've never been a huge user of img2img, so the script is pretty much focused on txt2img generation. The reason it works in img2img is mostly a happy accident.

So at the moment I don't have a good idea how to solve this without breaking a lot of other things. But I'll give it a try this weekend if I manage to set aside some time for it.

**Comment by yownas** [comment]
https://github.com/yownas/sd-webui-video-sa

I got curious what you could do with it. :)  Very experimental at the moment. It lacks a lot of functionality but should "work".

**Comment by mlsnr** [comment]
Awesome! Thanks so much :)
