### ISSUE TITLE
Video not generated. Installed moviepy not recognised?

### ISSUE THREAD

**Issue by strouder** [yownas/shift-attention#3]
moviepy is already installed... but when save results as video is on, it gives an error: "moviepy python module not installed. Will not be able to generate video."

Moviepy already installed
![3](https://user-images.githubusercontent.com/21327400/195502810-dd996913-a80f-4493-8754-3119973076ec.png)

Web UI settings
![4](https://user-images.githubusercontent.com/21327400/195502794-865267fd-6c14-48ec-95a9-7d4822fdce97.png)

Error
![5](https://user-images.githubusercontent.com/21327400/195502800-bfe0dca4-8032-41cf-b486-8521a71eb768.png)

**Comment by yownas** [comment]
The webui uses a virtual environment. Basically it creates it's own setup of modules so it doesn't have to depend on the systems python modules or accidentally overwrite something that might break other things... So.

The easiest way to get it to work is to add the line "moviepy==1.0.3" to requirements_versions.txt and let the it install things itself. 

The less easy way, if you want to install it manually, is to cd into the stable-diffusion-webui folder, type venv\Scripts\activate, install moviepy and then exit the virtual environment with venv\Scripts\deactivate.bat

**Comment by afewvowels** [comment]
I found the --ignore-installed tag also worked when trying to install moviepy after downloading the extension also worked in Google Colab:
```
!python -m pip install --ignore-installed moviepy
```
