### ISSUE TITLE
Does not support negative value to positive value (acrossing zero)

### ISSUE THREAD

**Issue by RTX10086** [yownas/shift-attention#6]
For example, if I write (dog:-1.0~1.3) the script will iterate from -1.0 to -1.3 instead of -1.0 to +1.3

I tried several times and found the script cannot move across 0, for example: 

-1.0 to 0, worked, 

0 to 1.0 worked

-1.0 to 1.0, does not work

or wait...... can we attach a negative value to a prompt under the WebUI syntax? Does (dog:-1.0) actually mean something or mean nothing and won't have any effect on the outcome? Thank you!

BTW, May I ask whether this script work for negative prompts or not? Cuz I'm thinking if **negative number on positive prompt** box isn't supported, then what if I use **positive number on negative prompt** box, would that be equivalent?

Thank you very much!

**Comment by yownas** [comment]
Thanks, I had missed that completely. Now negative numbers should work (again?).

I actually don't know exactly what stable diffusion think of negative values in the prompt, but it seems it is almost the same as writing it in the negative prompt. For example "cat:-1" (no parenthesis) seem to be the same as "cat" in the negative prompt. But "(cat:-1)" will give you a cat, but a different one from "cat". 

Either way... Negative number will work now. What they do is a completely different issue. :)

**Comment by RTX10086** [comment]
Thank you for the fixing and explanation!
