### ISSUE TITLE
I am really really begginer

### ISSUE THREAD

**Issue by Qwertzuy** [yownas/shift-attention#9]
It took me a while to find a way to contact you. I would have a problem that I already have my pictures, quite a lot, and I would like to apply the effects to them, not to create new ones. I use google colab and anythingv4.5.ipynb.
seed_travel and the
shift-attention.
Another question I would like to ask is this videographer on tiktok, which effect does he use and how?
https://www.tiktok.com/@proteinique/video/7205561738668821766

Thank you in advance for your help, sorry for my google translate english.

**Comment by Mic-N** [comment]
This probably isn't really the place for that sort of question or discussion, this is more for problems with this specific software.

You might try raising the question in a more general forum, something like https://www.reddit.com/r/StableDiffusion/ would likely get you more help

**Comment by yownas** [comment]
Hi.

I'm not sure how the Tiktok-video was made. But I've seen people use [Flowframes](https://nmkd.itch.io/flowframes) to get videos that look like that. Either starting with animation from Seed travel, or even just manually generated images and then let Flowframes generate a smoother video.

https://www.tiktok.com/@aicatgirls/video/7180556261396778286
